<select class="form-control col-sm-6" id='vehicle'>
    <option value="ADMIRAL">Admiral</option>
    <option value="ALPHA">Alpha</option>
    <option value="AMBULANCE">Ambulance</option>
    <option value="BF INJECTION">BF Injection</option>
    <option value="BF-400">BF-400</option>
    <option value="BMX">BMX</option>
    <option value="BAGGAGE">Baggage</option>
    <option value="BANDITO">Bandito</option>
    <option value="BANSHEE">Banshee</option>
    <option value="BARRACKS">Barracks</option>
    <option value="BENSON">Benson</option>
    <option value="BERKLEY'S RC Van">Berkley's RC Van</option>
    <option value="BIKE">Bike</option>
    <option value="BLADE">Blade</option>
    <option value="BLISTA COMPACT">Blista Compact</option>
    <option value="BLOODRING BANGER">Bloodring Banger</option>
    <option value="BOBCAT">Bobcat</option>
    <option value="BOXVILLE">Boxville</option>
    <option value="BRAVURA">Bravura</option>
    <option value="BROADWAY">Broadway</option>
    <option value="BUCCANEER">Buccaneer</option>
    <option value="BUFFALO">Buffalo</option>
    <option value="BULLET">Bullet</option>
    <option value="BURRITO">Burrito</option>
    <option value="BUS">Bus</option>
    <option value="CABBIE">Cabbie</option>
    <option value="CADDY">Caddy</option>
    <option value="CADRONA">Cadrona</option>
    <option value="CAMPER">Camper</option>
    <option value="CEMENT TRUCK">Cement Truck</option>
    <option value="CHEETAH">Cheetah</option>
    <option value="CLOVER">Clover</option>
    <option value="CLUB">Club</option>
    <option value="COACH">Coach</option>
    <option value="COMBINE HARVESTER">Combine Harvester</option>
    <option value="COMET">Comet</option>
    <option value="DFT-30">DFT-30</option>
    <option value="DOZER">Dozer</option>
    <option value="DUMPER">Dumper</option>
    <option value="DUNE">Dune</option>
    <option value="ELEGANT">Elegant</option>
    <option value="ELEGY">Elegy</option>
    <option value="EMPEROR">Emperor</option>
    <option value="ENFORCER">Enforcer</option>
    <option value="ESPERANTO">Esperanto</option>
    <option value="EUROS">Euros</option>
    <option value="FBI RANCHER">FBI Rancher</option>
    <option value="FBI TRUCK">FBI Truck</option>
    <option value="FCR-900">FCR-900</option>
    <option value="FAGGIO">Faggio</option>
    <option value="FELTZER">Feltzer</option>
    <option value="FIRE TRUCK">Fire Truck</option>
    <option value="FLASH">Flash</option>
    <option value="FLATBED">Flatbed</option>
    <option value="FORKLIFT">Forklift</option>
    <option value="FORTUNE">Fortune</option>
    <option value="FREEWAY">Freeway</option>
    <option value="GLENDALE">Glendale</option>
    <option value="GREENWOOD">Greenwood</option>
    <option value="HPV-1000">HPV-1000</option>
    <option value="HERMES">Hermes</option>
    <option value="HOTDOG">Hotdog</option>
    <option value="HOTKNIFE">Hotknife</option>
    <option value="HOTRING RACER">Hotring Racer</option>
    <option value="HUNTLEY">Huntley</option>
    <option value="HUSTLER">Hustler</option>
    <option value="INFERNUS">Infernus</option>
    <option value="INTRUDER">Intruder</option>
    <option value="JESTER">Jester</option>
    <option value="JOURNEY">Journey</option>
    <option value="KART">Kart</option>
    <option value="LANDSTALKER">Landstalker</option>
    <option value="LINERUNNER">Linerunner</option>
    <option value="MAJESTIC">Majestic</option>
    <option value="MANANA">Manana</option>
    <option value="MERIT">Merit</option>
    <option value="MESA">Mesa</option>
    <option value="MONSTER">Monster</option>
    <option value="MOONBEAM">Moonbeam</option>
    <option value="MOTHERSHIP">Mothership</option>
    <option value="MOUNTAIN BIKE">Mountain Bike</option>
    <option value="MOWER">Mower</option>
    <option value="MR WHOOPEE">Mr Whoopee</option>
    <option value="MULE">Mule</option>
    <option value="NRG-500">NRG-500</option>
    <option value="NEBULA">Nebula</option>
    <option value="NEWSVAN">Newsvan</option>
    <option value="OCEANIC">Oceanic</option>
    <option value="PCJ-600">PCJ-600</option>
    <option value="PACKER">Packer</option>
    <option value="PATRIOT">Patriot</option>
    <option value="PERENNIAL">Perennial</option>
    <option value="PHOENIX">Phoenix</option>
    <option value="PICADOR">Picador</option>
    <option value="PIZZABOY">Pizzaboy</option>
    <option value="POLICE">Police</option>
    <option value="PONY">Pony</option>
    <option value="PREMIER">Premier</option>
    <option value="PREVION">Previon</option>
    <option value="PRIMO">Primo</option>
    <option value="QUAD">Quad</option>
    <option value="RANCHER">Rancher</option>
    <option value="RANGER">Ranger</option>
    <option value="REGINA">Regina</option>
    <option value="REMINGTON">Remington</option>
    <option value="RHINO">Rhino</option>
    <option value="ROADTRAIN">Roadtrain</option>
    <option value="ROMERO">Romero</option>
    <option value="RUMPO">Rumpo</option>
    <option value="S.W.A.T.">S.W.A.T.</option>
    <option value="SABRE">Sabre</option>
    <option value="SADLER">Sadler</option>
    <option value="SANCHEZ">Sanchez</option>
    <option value="SANDKING">Sandking</option>
    <option value="SAVANNA">Savanna</option>
    <option value="SECURICAR">Securicar</option>
    <option value="SENTINEL">Sentinel</option>
    <option value="SLAMVAN">Slamvan</option>
    <option value="SOLAIR">Solair</option>
    <option value="STAFFORD">Stafford</option>
    <option value="STALLION">Stallion</option>
    <option value="STRATUM">Stratum</option>
    <option value="STRETCH">Stretch</option>
    <option value="SULTAN">Sultan</option>
    <option value="SUNRISE">Sunrise</option>
    <option value="SUPER GT">Super GT</option>
    <option value="SWEEPER">Sweeper</option>
    <option value="TAHOMA">Tahoma</option>
    <option value="TAMPA">Tampa</option>
    <option value="TANKER">Tanker</option>
    <option value="TAXI">Taxi</option>
    <option value="TORNADO">Tornado</option>
    <option value="TOW TRUCK">Tow Truck</option>
    <option value="TRACTOR">Tractor</option>
    <option value="TRASHMASTER">Trashmaster</option>
    <option value="TUG">Tug</option>
    <option value="TURISMO">Turismo</option>
    <option value="URANUS">Uranus</option>
    <option value="UTILITY VAN">Utility Van</option>
    <option value="VINCENT">Vincent</option>
    <option value="VIRGO">Virgo</option>
    <option value="VOODOO">Voodoo</option>
    <option value="VORTEX">Vortex</option>
    <option value="WALTON">Walton</option>
    <option value="WASHINGTON">Washington</option>
    <option value="WAYFARER">Wayfarer</option>
    <option value="WILLARD">Willard</option>
    <option value="WINDSOR">Windsor</option>
    <option value="YANKEE">Yankee</option>
    <option value="YOSEMITE">Yosemite</option>
    <option value="ZR-350">ZR-350</option>
</select>
